### ISSUE TITLE
HTTPS sitemap

### ISSUE THREAD

**Issue by jasonrogena** [jekyll/jekyll-sitemap#70] opened 2015-02-06 14:31 UTC
Is it possible to configure the plugin to generate only https links in the sitemap.xml file?

**Comment by pathawks** [comment] 2015-02-06 16:02
If `site.url` in your `_config.yml` file is an HTTPS URL, then all of the links in your `sitemap.xml` file *will* be only HTTPS URLs.

**Comment by parkr** [comment] 2015-02-06 21:11
If you don't have a `site.url` and you're publishing to GitHub, you will not see `https://`. The only way is to set `site.url` to a value with `https://`.

**Comment by XhmikosR** [comment] 2015-04-02 15:27
While this works fine, the generated sitemap.xml has mixed content thus it's not valid.

I have not been able to find a solution to this yet...

**Comment by parkr** [comment] 2015-04-02 16:55
> the generated sitemap.xml has mixed content thus it's not valid.

What do you mean by this?

**Comment by XhmikosR** [comment] 2015-04-02 17:58
The xml references use http resulting in mixed content. I tried using https
but fails.

**Comment by parkr** [comment] 2015-04-02 18:14
> xml references use http

Should they always use https? Or is it only valid if all the url protocols match?

**Comment by XhmikosR** [comment] 2015-04-02 18:16
Https needs everything https otherwise we have mixed content issues. Http
works with both fine.

Were you able to find a fix for this? I have the same issue for RSS feeds
and I had to force http for that :/

**Comment by pathawks** [comment] 2015-04-03 22:20
```xml
<urlset xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.sitemaps.org/schemas/sitemap/0.9 http://www.sitemaps.org/schemas/sitemap/0.9/sitemap.xsd" xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
```

These are URIs rather than URLs. The sitemap is no longer valid if you change the `xmlns` to `https://www.sitemaps.org/schemas/sitemap/0.9`; it doesn't mean the same thing.

Even if that weren't the case, `sitemaps.org` is not available over *HTTPS*, so what are ya gonna do?

As to the "mixed content issues," I'm not sure where you are getting that from. Anything that knows how to parse sitemaps (or XML, for that matter) should not be trying to display anything from those addresses. Can you point to an example of a problem you have encountered?

**Comment by XhmikosR** [comment] 2015-04-03 22:28
It has mixed content, that is for sure. The fact that sitemap.xml isn't supposed to be parsed by normal browsers is something that doesn't make the issue known to most, but doesn't magically solve the issue. Unless it's a bug of the browser, but this happens with Firefox too.

Example: https://mpc-hc.org/sitemap.xml. Try with Internet Explorer and you'll see what I mean; it just don't loads it due to mixed content.

![2015-04-04_01-25-39](https://cloud.githubusercontent.com/assets/349621/6989856/ada0d87c-da69-11e4-8628-43d020ce74b8.png)

Like I said, I'm facing the same issue with RSS feeds. The problem is way more obvious there.

**Comment by pathawks** [comment] 2015-04-03 23:21
It loads for me in Internet Explorer, Firefox, Chrome, and Safari, no problem. In fact, it looks like it loaded for you as well, judging by the screenshot you posted.

Again I ask: Can you point to an example of a problem you have encountered?

**Comment by XhmikosR** [comment] 2015-04-04 06:37
See the screenshot. It loads but it has mixed content.

![2015-04-04_09-36-36](https://cloud.githubusercontent.com/assets/349621/6991720/22f3beb6-daae-11e4-8c6e-ba274984bd6b.png)

**Comment by parkr** [comment] 2015-04-11 04:45
Let's just hard-code HTTPS wherever we're hard-coding. Anyone have time for a PR?

**Comment by XhmikosR** [comment] 2015-04-11 04:46
That would work if it was available :/

There's no `https://www.sitemaps.org/schemas/sitemap/0.9 https://www.sitemaps.org/schemas/sitemap/0.9/sitemap.xsd`.

**Comment by parkr** [comment] 2015-04-11 05:12
Oh. Then there's really nothing we can do :person_frowning:

**Comment by XhmikosR** [comment] 2015-04-11 05:13
Yeah, I know. I'm looking for a solution for this, for a long time.

**Comment by parkr** [comment] 2015-04-11 05:15
Could we host these on a GitHub Pages site, like `https://sitemaps.github.io`?

**Comment by XhmikosR** [comment] 2015-04-11 05:16
That should work, I think.

**Comment by pathawks** [comment] 2015-04-11 05:31
Host what?
Remember, these are Uniform Resource *Identifiers*, not *locators*. Changing the value changes the syntactic meaning, making the sitemap no longer valid.

It makes no difference if the file they point to is the same, that’s not what matters.

**Comment by parkr** [comment] 2015-04-11 05:32
@pathawks Then we're stuck. :(

**Closed by parkr** 2015-04-11 05:32 UTC
