### ISSUE TITLE
Option to disable/omit lastmod

### ISSUE THREAD

**Issue by sethladd** [jekyll/jekyll-sitemap#62] opened 2014-12-11 23:16 UTC
When generating html_pages, the lastmod doesn't quite make sense. Sure, the page was just regenerated, but doesn't mean the content changed.

We'd love an option to omit the lastmod tag when generating a sitemap.

Thanks!

**Comment by pathawks** [comment] 2015-01-15 06:47
This is pretty much a duplicate of #35

**Closed** 2015-02-08 04:54 UTC

**Comment by cbeams** [comment] 2017-02-24 09:23
Heads up: I've been unable to omit `<lastmod>` from my sitemap in any case. See  cbeams/chris.beams.io@e074b6d for details. Happy to create a new issue for this, but thought I'd mention it here first in case I've just missed something.
